name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  nodejs:
    uses: zakodium/workflows/.github/workflows/nodejs.yml@nodejs-v1
    with:
      node-version: 24.x
      lint-check-types: true
      npm-test-command: npm run build
      node-version-matrix: '[24]'
      upload-coverage: false
      disable-test-package: true
