name: Check spelling

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v7
        with:
          config: ./cspell.config.yaml
          files: |
            **/*.md
